name: Inspect Pull Requests

on:
  pull_request:
    branches: [main]

env:
  COREPACK_ENABLE_STRICT: 0

jobs:
  bundlesize:
    if: ${{ always() }}
    needs: release-bundlesize
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      pull-requests: write
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          corepack enable
          pnpm install
          npx lerna run build:bundlesize
          npx lerna run stats:pr --scope=@mylogin/client
          npx lerna run stats:report --scope=@mylogin/client
      - uses: mshick/add-pr-comment@v2
        if: always()
        with:
          refresh-message-position: true
          message-path: packages/client/tmp/pr-stats.md

  inspect:
    if: ${{ always() }}
    needs: release-bundlesize
    runs-on: blacksmith-4vcpu-ubuntu-2204
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          corepack enable
          pnpm install
          npx lerna run build
          npx lerna run lint
          npx lerna run test:coverage

  release-bundlesize:
    if: github.head_ref == 'release-please--branches--main--components--client'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.NODE_CLI }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          corepack enable
          pnpm install
          npx lerna run build:bundlesize
          npx lerna run stats:release --scope=@mylogin/client
      - name: Commit Release Stats
        uses: stefanzweifel/git-auto-commit-action@v5
