name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  COREPACK_ENABLE_STRICT: 0

jobs:
  release-please:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.NODE_CLI }}

      - name: Checkout Repository
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4

      - name: Setup Node
        uses: useblacksmith/setup-node@v5
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"

      - name: Build Packages
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          corepack enable
          pnpm install
          npx lerna run build
